version: '2'

services:
    masternode:
        image: kunstmaan/master-multichain
        build: ./master
        stdin_open: true
        tty: true
        ports:
            - "7447:7447"
            - "8000:8000"
        environment:
            VIRTUAL_HOST: mulichain-master.docker
            VIRTUAL_PORT: 8000
    explorer:
        image: kunstmaan/explorer-multichain
        build: ./explorer
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        ports:
            - "2750:2750"
        environment:
            VIRTUAL_HOST: multichain-explorer.docker
            VIRTUAL_PORT: 2750
        links:
            - masternode
    slavenode1:
        image: kunstmaan/node-multichain
        build: ./node
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        links:
            - masternode
    slavenode2:
        image: kunstmaan/node-multichain
        build: ./node
        stdin_open: true
        tty: true
        depends_on:
            - masternode
        links:
            - masternode
